export const Labels = {
    HOME: "Home",
    SURFING: "Surfing",
    HULA: "Hula",
    VULCANO: "Vulcano",
    BOOK_TRIP: "Book a trip",
    HIGHLIGHTS: "Highlights",
    ADVENTURE: "Adventure",
    CULINARY: "Culinary",
    ECO_TOURISM: "Eco-tourism",
    FAMILY: "Family",
    SPORT: "Sports",
    VULCANOES: "Vulcanoes",
    SURF_DESC: "Best Hawaiian islands for surfing.",
    HULA_DESC: "Try it yourself.",
    VUL_DESC: "Volcanic conditions can change at any time.",
    CATEGORIES: "Catergories",
    TRAVEL_GUIDE: "Travel Guide",
    CONTACT: "Contact",
    CONTACT_NAME: "Hadwin Malone",
    CONTACT_DETAIL: "Guide since 2012",
    BOOK_NOW: "Book a trip",
    SURF_DETAIL: "Hawaii is the capital of modern surfing. This group of Pacific islands gets swell from all directions, so there are plenty of pristine surf spots for all.",
    TOP_SPOT: "Top spots"
}